import { Inter } from "next/font/google";
import Navigation from "@/componets/Navigation";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My First App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Navigation />
        {children}
        </body>
    </html>
  );
}
